-- CreateTable
CREATE TABLE "AUTORIZACIONWEB" (
    "ID" SERIAL NOT NULL,
    "ORDEN_SERVICIO" INTEGER,
    "FECHA_ORDEN" TIMESTAMP(6),
    "PRESTADOR_DOCUMENTO_ID" VARCHAR(20),
    "NUMERO_POLIZA" INTEGER,
    "NUMERO_FAMILIA" INTEGER,
    "NUMERO_AFILIADO" INTEGER,
    "BENEFICIARIO_DOCUMENTO_ID" VARCHAR(20),
    "FECHA_CREACION" TIMESTAMP(6),
    "USUARIO_CREACION_ID" VARCHAR(20),

    CONSTRAINT "AUTORIZACIONWEB_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "AUTORIZACIONWEBDETALLE" (
    "ID" SERIAL NOT NULL,
    "AUTORIZACIONWEB_ID" INTEGER,
    "ORDEN_SERVICIO" INTEGER,
    "CODIGO_SERVICIO" VARCHAR(100),
    "CANTIDAD_SERVICIO" INTEGER,
    "CODIGO_DIAGNOSTICO" VARCHAR(255),
    "VALOR_ECUSANITAS" DOUBLE PRECISION,
    "VALOR_CUBIERTO" DOUBLE PRECISION,
    "VALOR_COPAGO_TOTAL" DOUBLE PRECISION,
    "VALOR_DEDUCIBLE" DOUBLE PRECISION,
    "PORCENTAJE_COBERTURA" DOUBLE PRECISION,
    "COPAGO_MINIMO" DOUBLE PRECISION,
    "VALOR_DESCUENTO" DOUBLE PRECISION,
    "CODIGO_DIAGNOSTICO_ORIGEN" VARCHAR(255),

    CONSTRAINT "AUTORIZACIONWEBDETALLE_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE INDEX "idx_fecha_creacion" ON "AUTORIZACIONWEB"("FECHA_CREACION");

-- CreateIndex
CREATE INDEX "idx_fecha_orden" ON "AUTORIZACIONWEB"("FECHA_ORDEN");

-- CreateIndex
CREATE INDEX "idx_numero_poliza" ON "AUTORIZACIONWEB"("NUMERO_POLIZA");

-- CreateIndex
CREATE INDEX "idx_orden_servicios" ON "AUTORIZACIONWEB"("ORDEN_SERVICIO");

-- CreateIndex
CREATE INDEX "idx_codigo_servicio" ON "AUTORIZACIONWEBDETALLE"("CODIGO_SERVICIO");

-- CreateIndex
CREATE INDEX "idx_diagnostico" ON "AUTORIZACIONWEBDETALLE"("CODIGO_DIAGNOSTICO");

-- CreateIndex
CREATE INDEX "idx_orden_servicio" ON "AUTORIZACIONWEBDETALLE"("ORDEN_SERVICIO");

-- AddForeignKey
ALTER TABLE "AUTORIZACIONWEBDETALLE" ADD CONSTRAINT "AUTORIZACIONWEBDETALLE_AUTORIZACIONWEB_ID_fkey" FOREIGN KEY ("AUTORIZACIONWEB_ID") REFERENCES "AUTORIZACIONWEB"("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
